// Package substrate (continued).
//
// Embedded substrate is the always-present fallback layer of the
// resolver chain. The data/ tree is a mirror of the project's
// .scion/templates/, scripts/, images/, and host-mode skills,
// regenerated by `make sync-embed-data` (added in Task 6).
//
// We mirror into the package because Go's //go:embed cannot reference
// files outside the package's directory tree.
package substrate

import (
	"crypto/sha256"
	"embed"
	"encoding/hex"
	"io/fs"
	"sync"
)

//go:embed all:data
var embeddedFS embed.FS

// EmbeddedFS returns the binary's embedded substrate as an fs.FS.
// Paths are rooted at "data/" — e.g. "data/.scion/templates/researcher/scion-agent.yaml".
func EmbeddedFS() fs.FS {
	return embeddedFS
}

var (
	hashOnce sync.Once
	hashStr  string
)

// EmbeddedHash returns a SHA-256 hex digest of the embedded tree's
// concatenated contents (path + body, sorted by path). Stable across
// builds of the same source. Surfaced by `darken version`.
func EmbeddedHash() string {
	hashOnce.Do(func() {
		h := sha256.New()
		_ = fs.WalkDir(embeddedFS, ".", func(path string, d fs.DirEntry, err error) error {
			if err != nil || d.IsDir() {
				return err
			}
			body, _ := fs.ReadFile(embeddedFS, path)
			h.Write([]byte(path))
			h.Write([]byte{0})
			h.Write(body)
			return nil
		})
		hashStr = hex.EncodeToString(h.Sum(nil))
	})
	return hashStr
}
